# Indian & commonly prescribed medicines — demo side-effects info (not medical advice).
# Keys are lowercase for lookup; consult a doctor/pharmacist for real decisions.


def _e(name, med_type, common, serious, interactions, warnings, severity):
    return {
        "name": name,
        "type": med_type,
        "common_side_effects": common,
        "serious_side_effects": serious,
        "interactions": interactions,
        "warnings": warnings,
        "severity": severity,
    }


# Primary entries (canonical keys)
_BASE = {
    "amlong": _e(
        "Amlodipine (Amlong)",
        "Antihypertensive (CCB)",
        ["Swelling in feet/ankles", "Headache", "Dizziness", "Flushing"],
        ["Chest pain", "Severe dizziness", "Fainting", "Irregular heartbeat"],
        ["Grapefruit juice", "Simvastatin", "Other BP medicines"],
        "Do not stop suddenly. Monitor BP regularly.",
        "MEDIUM",
    ),
    "metformin": _e(
        "Metformin (e.g. Glycomet)",
        "Antidiabetic (Biguanide)",
        ["Nausea", "Diarrhea", "Metallic taste", "Loss of appetite"],
        ["Lactic acidosis (rare)", "Vitamin B12 deficiency with long use"],
        ["Alcohol", "IV contrast dye", "Heavy alcohol use"],
        "Take with meals. Kidney function should be monitored.",
        "MEDIUM",
    ),
    "aspirin": _e(
        "Aspirin (e.g. Disprin)",
        "NSAID / Antiplatelet",
        ["Stomach upset", "Heartburn", "Easy bruising"],
        ["Bleeding (GI or brain)", "Severe allergy", "Reye syndrome in children"],
        ["Warfarin", "Other NSAIDs", "Alcohol"],
        "Avoid in children with viral illness unless prescribed. Bleeding risk.",
        "HIGH",
    ),
    "crocin": _e(
        "Crocin / Paracetamol",
        "Analgesic / Antipyretic",
        ["Rare at normal dose", "Nausea if sensitive"],
        ["Liver injury with overdose", "Severe skin reactions (rare)"],
        ["Alcohol", "Other liver-toxic drugs", "Overdose"],
        "Max daily dose limits — do not exceed. Check all combo cold meds for paracetamol.",
        "MEDIUM",
    ),
    "dolo 650": _e(
        "Dolo 650 (Paracetamol 650 mg)",
        "Analgesic / Antipyretic",
        ["Mild nausea", "Rare rash"],
        ["Liver toxicity if overdosed"],
        ["Alcohol", "Other paracetamol-containing products"],
        "Count total paracetamol from all sources in 24 hours.",
        "MEDIUM",
    ),
    "calpol": _e(
        "Calpol (Paracetamol — pediatric)",
        "Analgesic / Antipyretic",
        ["Rare stomach upset"],
        ["Overdose — liver damage", "Wrong strength for age"],
        ["Other syrups with paracetamol"],
        "Use dose by weight/age as on label or as doctor advised.",
        "MEDIUM",
    ),
    "combiflam": _e(
        "Combiflam (Ibuprofen + Paracetamol)",
        "NSAID + Analgesic combo",
        ["Stomach pain", "Nausea", "Heartburn", "Dizziness"],
        ["Stomach bleeding", "Kidney problems", "Allergic reactions"],
        ["Other NSAIDs", "Blood thinners", "Alcohol", "Steroids"],
        "Take with food. Not for long unsupervised use. Avoid in late pregnancy.",
        "HIGH",
    ),
    "ibugesic": _e(
        "Ibugesic (Ibuprofen)",
        "NSAID",
        ["Stomach upset", "Dizziness", "Heartburn"],
        ["GI bleeding", "Kidney injury", "Stroke/MI risk with long high dose"],
        ["Aspirin", "Warfarin", "Alcohol"],
        "Take with food. Caution if kidney or heart disease.",
        "HIGH",
    ),
    "rantac": _e(
        "Rantac (Ranitidine — many use ‘Rentac’ spelling)",
        "H2 blocker (reduces stomach acid)",
        ["Headache", "Constipation or diarrhea", "Dizziness"],
        ["Liver issues (rare)", "Slow heart rate (rare)"],
        ["Certain antifungals", "Some HIV meds"],
        "Long-term acid symptoms need doctor evaluation. Formulations vary by region.",
        "LOW",
    ),
    "roko": _e(
        "Roko (Loperamide)",
        "Antidiarrheal",
        ["Constipation", "Bloating", "Dizziness"],
        ["Severe constipation", "Allergic reaction"],
        ["QT-prolonging drugs", "Some antibiotics"],
        "Do not use if bloody stool or high fever without doctor — may mask serious infection.",
        "MEDIUM",
    ),
    "nicip plus": _e(
        "Nicip Plus (Nimesulide + Paracetamol)",
        "NSAID combo (country-specific availability)",
        ["Nausea", "Heartburn", "Dizziness"],
        ["Liver injury (nimesulide risk)", "GI bleeding", "Kidney issues"],
        ["Other NSAIDs", "Alcohol", "Warfarin"],
        "Banned or restricted in some countries. Short courses only if prescribed.",
        "HIGH",
    ),
    "nicip": _e(
        "Nicip (Nimesulide)",
        "NSAID",
        ["Nausea", "Heartburn", "Dizziness"],
        ["Liver toxicity", "GI bleeding"],
        ["Alcohol", "Other NSAIDs", "Paracetamol combos — watch total dose"],
        "Use only as prescribed; not first-line in many guidelines.",
        "HIGH",
    ),
    "diclogem": _e(
        "Diclogem (Diclofenac + Paracetamol typical combo)",
        "NSAID + Analgesic",
        ["Stomach pain", "Nausea", "Heartburn"],
        ["GI bleeding", "Kidney injury", "Cardiovascular risk (long-term)"],
        ["Aspirin", "Blood thinners", "Alcohol", "SSRIs"],
        "Take with food. Caution in heart, kidney, or ulcer disease.",
        "HIGH",
    ),
    "voveran": _e(
        "Voveran (Diclofenac)",
        "NSAID",
        ["Stomach upset", "Nausea", "Dizziness"],
        ["GI bleeding", "Kidney problems", "Raised BP"],
        ["Lithium", "Methotrexate", "Diuretics", "Alcohol"],
        "Gel vs tablet — different risks. Oral NSAIDs need caution.",
        "HIGH",
    ),
    "oxalgin": _e(
        "Oxalgin / Oxalgin-D (often Aceclofenac ± Paracetamol)",
        "NSAID-based pain relief",
        ["Nausea", "Indigestion", "Dizziness"],
        ["GI bleeding", "Liver enzyme changes", "Kidney issues"],
        ["Other NSAIDs", "Blood thinners", "Alcohol"],
        "Confirm exact composition on strip. Take with food.",
        "HIGH",
    ),
    "zerodol": _e(
        "Zerodol (Aceclofenac + Paracetamol common)",
        "NSAID combo",
        ["Stomach upset", "Heartburn", "Dizziness"],
        ["GI bleeding", "Allergic reaction"],
        ["Other NSAIDs", "Warfarin", "Alcohol"],
        "Short courses for pain/inflammation as prescribed.",
        "HIGH",
    ),
    "enzoflam": _e(
        "Enzoflam (Diclofenac + enzymes — brand variants exist)",
        "NSAID + enzyme supplement",
        ["Nausea", "Stomach discomfort", "Diarrhea"],
        ["GI bleeding", "Allergic reaction"],
        ["Other NSAIDs", "Anticoagulants"],
        "Check exact ingredients on pack. Not for empty stomach long-term.",
        "HIGH",
    ),
    "saridon": _e(
        "Saridon (Paracetamol + Propyphenazone + Caffeine)",
        "Analgesic combo",
        ["Insomnia if taken late", "Palpitations (caffeine)", "Nausea"],
        ["Liver injury if overdosed", "Allergic reactions"],
        ["Alcohol", "Other paracetamol products"],
        "Avoid frequent use. Contains caffeine — may disturb sleep.",
        "MEDIUM",
    ),
    "disprin": _e(
        "Disprin (Aspirin)",
        "NSAID / Antiplatelet",
        ["Stomach irritation", "Tinnitus at high dose"],
        ["Bleeding", "Asthma exacerbation in sensitive people"],
        ["Warfarin", "NSAIDs", "Alcohol"],
        "Dissolved form — still GI risk. Not for children with viral illness.",
        "HIGH",
    ),
    "gelusil": _e(
        "Gelusil (Antacid — Al/Mg hydroxide typical)",
        "Antacid",
        ["Constipation or diarrhea", "Chalky taste"],
        ["Electrolyte imbalance with overuse", "Kidney issues (rare)"],
        ["Some antibiotics (reduced absorption)", "Iron supplements"],
        "Space apart from other medicines as advised.",
        "LOW",
    ),
    "digene": _e(
        "Digene (Antacid chewable)",
        "Antacid",
        ["Constipation", "Gas"],
        ["High calcium load if wrong product variant — read label"],
        ["Tetracyclines", "Iron", "Thyroid meds — timing matters"],
        "Chew well. Separate from drugs that need empty stomach.",
        "LOW",
    ),
    "eno": _e(
        "Eno (Antacid powder)",
        "Antacid (sodium salts)",
        ["Bloating", "Gas relief"],
        ["High sodium — caution in BP/heart failure", "Alkalosis if overused"],
        ["Diuretics", "High salt diet"],
        "Not for long-term self-treatment of recurring acidity.",
        "LOW",
    ),
    "meftal spas": _e(
        "Meftal-Spas (Dicyclomine + Mefenamic acid typical)",
        "Antispasmodic + NSAID",
        ["Dry mouth", "Dizziness", "Constipation", "Stomach pain"],
        ["GI bleeding", "Allergic reaction"],
        ["Other NSAIDs", "Blood thinners"],
        "Common for cramps — still NSAID risks apply.",
        "HIGH",
    ),
    "cyclopam": _e(
        "Cyclopam (Dicyclomine + Paracetamol typical)",
        "Antispasmodic + Analgesic",
        ["Dry mouth", "Blurred vision", "Drowsiness"],
        ["Glaucoma worsening", "Urinary retention"],
        ["Alcohol", "Other sedatives"],
        "Avoid driving if drowsy. Caution in glaucoma/BPH.",
        "MEDIUM",
    ),
    "drotin": _e(
        "Drotin (Drotaverine)",
        "Antispasmodic",
        ["Nausea", "Dizziness", "Headache"],
        ["Allergic reaction (rare)", "Low BP (rare)"],
        ["Alcohol", "Other CNS depressants"],
        "Often used for spasmodic pain as prescribed.",
        "LOW",
    ),
    "domstal": _e(
        "Domstal (Domperidone)",
        "Prokinetic / Antiemetic",
        ["Dry mouth", "Headache", "Diarrhea"],
        ["QT prolongation (rare)", "Hormone changes (rare)"],
        ["Ketoconazole", "Erythromycin", "QT drugs"],
        "Dose limits in some regions. Cardiac risk if risk factors.",
        "MEDIUM",
    ),
    "ondem": _e(
        "Ondem (Ondansetron)",
        "Antiemetic",
        ["Constipation", "Headache", "Fatigue"],
        ["Serotonin syndrome (with serotonergic drugs)", "QT prolongation"],
        ["SSRIs", "Tramadol", "Other QT drugs"],
        "For nausea/vomiting as prescribed — especially chemo/post-op.",
        "MEDIUM",
    ),
    "avil": _e(
        "Avil (Pheniramine)",
        "Antihistamine",
        ["Drowsiness", "Dry mouth", "Blurred vision"],
        ["Urinary retention", "Severe sedation with alcohol"],
        ["Alcohol", "Other sedatives"],
        "May impair driving. Caution in glaucoma and prostate issues.",
        "MEDIUM",
    ),
    "allegra": _e(
        "Allegra (Fexofenadine)",
        "Antihistamine (non-sedating)",
        ["Headache", "Nausea (uncommon)"],
        ["Allergic reaction to drug (rare)"],
        ["Fruit juice can reduce absorption — take with water"],
        "Less sedating than older antihistamines.",
        "LOW",
    ),
    "cetirizine": _e(
        "Cetirizine (e.g. Okacet, CTZ)",
        "Antihistamine",
        ["Mild drowsiness", "Dry mouth"],
        ["Rare palpitations", "Allergic reaction"],
        ["Alcohol", "CNS depressants"],
        "Some people feel sleepy — avoid hazardous work if affected.",
        "LOW",
    ),
    "montair": _e(
        "Montair (Montelukast)",
        "Leukotriene blocker (asthma/allergy)",
        ["Headache", "Stomach upset", "Thirst"],
        ["Mood changes or sleep issues (reported — rare)", "Allergic reaction"],
        ["Phenytoin", "Rifampin (may interact)"],
        "For allergic rhinitis/asthma as prescribed. Report mood changes.",
        "MEDIUM",
    ),
    "azithral": _e(
        "Azithral (Azithromycin)",
        "Macrolide antibiotic",
        ["Nausea", "Diarrhea", "Stomach pain"],
        ["QT prolongation", "Severe diarrhea (C. diff)", "Liver issues"],
        ["Warfarin", "Statins", "Antiarrhythmics"],
        "Complete course if prescribed. May cause irregular heartbeat with risk factors.",
        "MEDIUM",
    ),
    "augmentin": _e(
        "Augmentin (Amoxicillin + Clavulanic acid)",
        "Antibiotic",
        ["Diarrhea", "Nausea", "Thrush"],
        ["Severe allergy", "Liver issues (rare)", "C. diff colitis"],
        ["Methotrexate", "Warfarin", "Probenecid"],
        "Take with food often helps. Finish course unless told to stop.",
        "MEDIUM",
    ),
    "norflox": _e(
        "Norflox (Norfloxacin)",
        "Fluoroquinolone antibiotic",
        ["Nausea", "Dizziness", "Headache"],
        ["Tendon rupture", "Neuropathy", "QT prolongation"],
        ["NSAIDs", "Steroids", "Theophylline", "Warfarin"],
        "Avoid in children; reserve for indicated infections. Sun sensitivity.",
        "HIGH",
    ),
    "metrogyl": _e(
        "Metrogyl (Metronidazole)",
        "Antibiotic / Antiprotozoal",
        ["Metallic taste", "Nausea", "Dark urine"],
        ["Neuropathy with long use", "Severe allergy"],
        ["Alcohol (disulfiram-like reaction)", "Warfarin"],
        "Absolutely avoid alcohol during and 48h after course.",
        "HIGH",
    ),
    "omez": _e(
        "Omez (Omeprazole)",
        "PPI (reduces stomach acid)",
        ["Headache", "Diarrhea", "Gas"],
        ["Low magnesium/B12 with long use", "Bone fracture risk (long-term)"],
        ["Clopidogrel interaction (debated)", "Some antifungals"],
        "Short courses for acidity. Long-term needs review.",
        "MEDIUM",
    ),
    "pantocid": _e(
        "Pantocid (Pantoprazole)",
        "PPI",
        ["Headache", "Diarrhea", "Abdominal pain"],
        ["Kidney issues (rare)", "Low magnesium"],
        ["Methotrexate", "Warfarin", "Clopidogrel"],
        "Take before food as directed. Not for instant relief like antacids.",
        "MEDIUM",
    ),
    "telma": _e(
        "Telma (Telmisartan)",
        "ARB (blood pressure)",
        ["Dizziness", "Fatigue", "Raised potassium (rare)"],
        ["Kidney problems", "Severe hypotension", "Angioedema (rare)"],
        ["Potassium supplements", "NSAIDs", "Lithium"],
        "Avoid in pregnancy. Monitor kidney function and potassium.",
        "MEDIUM",
    ),
    "amlopres": _e(
        "Amlopres (Amlodipine)",
        "CCB antihypertensive",
        ["Ankle swelling", "Flushing", "Headache"],
        ["Severe hypotension", "Worsening angina (rare)"],
        ["Simvastatin", "Grapefruit"],
        "Same class as Amlong — swelling common.",
        "MEDIUM",
    ),
    "stamlo": _e(
        "Stamlo (Amlodipine)",
        "CCB antihypertensive",
        ["Swelling", "Palpitations", "Headache"],
        ["Heart failure worsening if inappropriate", "Severe hypotension"],
        ["Other BP meds", "Grapefruit"],
        "Regular BP checks when starting or changing dose.",
        "MEDIUM",
    ),
    "glycomet": _e(
        "Glycomet (Metformin)",
        "Antidiabetic",
        ["GI upset", "Metallic taste"],
        ["Lactic acidosis (very rare)", "B12 deficiency"],
        ["Contrast dye", "Alcohol"],
        "Same as generic metformin — kidney dosing matters.",
        "MEDIUM",
    ),
    "insulin": _e(
        "Insulin (Mixtard / Huminsulin / various)",
        "Antidiabetic (hormone)",
        ["Weight gain", "Injection site reactions", "Hypoglycemia"],
        ["Severe hypoglycemia", "Allergy"],
        ["Beta blockers (may mask low sugar symptoms)", "Alcohol"],
        "Rotate injection sites. Always carry fast sugar for lows.",
        "HIGH",
    ),
    "thyronorm": _e(
        "Thyronorm (Levothyroxine)",
        "Thyroid hormone",
        ["Palpitations if dose high", "Insomnia", "Sweating"],
        ["Chest pain", "Osteoporosis with excess long-term", "Arrhythmia"],
        ["Iron/calcium — separate timing", "Warfarin", "Some seizure meds"],
        "Take empty stomach, same time daily. Dose adjustments only with lab tests.",
        "MEDIUM",
    ),
    "revital": _e(
        "Revital (Multivitamin + minerals)",
        "Dietary supplement",
        ["Nausea if empty stomach", "Bright yellow urine (B vitamins)"],
        ["Iron overload if duplicated with other iron", "Hypercalcemia (rare)"],
        ["Tetracyclines with iron/zinc", "Levodopa with iron"],
        "Supplement — not a substitute for diet or prescribed meds.",
        "LOW",
    ),
    "becosules": _e(
        "Becosules (B-complex + Vitamin C)",
        "Vitamin supplement",
        ["Mild nausea", "Yellow urine"],
        ["Rare allergy"],
        ["Methotrexate (high folic context — doctor manages)"],
        "Often used with antibiotics or poor intake — follow label.",
        "LOW",
    ),
    "dexorange": _e(
        "Dexorange (Iron + Folic + B12 typical)",
        "Hematinic",
        ["Constipation", "Dark stools", "Nausea"],
        ["Iron overload if overdose", "Severe allergy"],
        ["Levothyroxine", "Tetracyclines", "Antacids — spacing"],
        "Take as directed for anemia — confirm cause with doctor.",
        "MEDIUM",
    ),
    "sinarest": _e(
        "Sinarest (Paracetamol + Phenylephrine + CPM typical)",
        "Cold combination",
        ["Drowsiness", "Dry mouth", "Raised BP from decongestant"],
        ["Severe hypertension", "Urinary retention", "Angle-closure glaucoma"],
        ["MAOIs", "Other sedatives", "Alcohol"],
        "Many cold meds duplicate paracetamol — read all labels.",
        "MEDIUM",
    ),
    "vicks action 500": _e(
        "Vicks Action 500+ (combo cold brand)",
        "Cold / analgesic combo",
        ["Drowsiness", "Dry mouth", "Nausea"],
        ["Liver toxicity if paracetamol exceeded", "Bleeding risk if contains aspirin variants"],
        ["Alcohol", "Other paracetamol products"],
        "Check exact active ingredients on pack each time.",
        "MEDIUM",
    ),
    "ors": _e(
        "ORS (Oral Rehydration Salts)",
        "Rehydration",
        ["Mild bloating", "Nausea if too fast"],
        ["Fluid overload in kidney/heart failure if not supervised"],
        ["None typical"],
        "Correct mixing as per sachet — important in diarrhea.",
        "LOW",
    ),
    "limcee": _e(
        "Limcee (Vitamin C)",
        "Vitamin supplement",
        ["Diarrhea at high dose", "Heartburn"],
        ["Kidney stones in predisposed people at megadoses"],
        ["None major"],
        "Usually well tolerated at normal doses.",
        "LOW",
    ),
    "betadine gargle": _e(
        "Betadine Gargle (Povidone-iodine)",
        "Antiseptic gargle",
        ["Thyroid tests can be affected if swallowed often", "Irritation"],
        ["Iodine allergy", "Thyroid disorder caution"],
        ["None major typical"],
        "Do not swallow. Short-term use for throat hygiene.",
        "LOW",
    ),
    "honitus": _e(
        "Honitus / Benadryl cough (brands vary)",
        "Cough syrup (composition varies)",
        ["Drowsiness", "Nausea"],
        ["Respiratory depression if mixed with sedatives", "Dependence with codeine variants"],
        ["Alcohol", "Opioids", "Benzodiazepines"],
        "Read label — some contain alcohol or codeine.",
        "HIGH",
    ),
    "strepsils": _e(
        "Strepsils (Lozenges)",
        "Soothing throat",
        ["Local irritation", "Allergic reaction (rare)"],
        ["Choking hazard in young children"],
        ["None significant"],
        "For sore throat comfort — not for bacterial infection cure alone.",
        "LOW",
    ),
    "moov": _e(
        "Moov / Volini (Topical analgesic)",
        "Topical NSAID / counterirritant",
        ["Skin irritation", "Rash", "Burning"],
        ["Systemic NSAID effects if over-applied on large area"],
        ["Open wounds", "Other topical meds same site"],
        "Wash hands; don’t use on broken skin unless label allows.",
        "LOW",
    ),
    "volini": _e(
        "Volini Spray/Gel (Topical pain)",
        "Topical analgesic",
        ["Skin irritation", "Menthol burn"],
        ["Allergic dermatitis"],
        ["Heating pads — avoid burns"],
        "External use only.",
        "LOW",
    ),
    "liv 52": _e(
        "Liv 52 (Herbal liver support — brand)",
        "Herbal supplement",
        ["Mild GI upset (rare)"],
        ["Not substitute for treating hepatitis/cirrhosis medically"],
        ["Unknown herb–drug interactions possible"],
        "Discuss with doctor if liver disease — evidence varies.",
        "LOW",
    ),
    "pudin hara": _e(
        "Pudin Hara (Peppermint oil — brand)",
        "Herbal digestive",
        ["Heartburn in some", "Allergic reaction (rare)"],
        ["GERD may worsen in sensitive people"],
        ["None major"],
        "Traditional remedy for gas/bloating — mild symptoms only.",
        "LOW",
    ),
    "enterogermina": _e(
        "Enterogermina (Probiotic)",
        "Probiotic",
        ["Gas", "Bloating initially"],
        ["Infection in immunocompromised (theoretical)"],
        ["Antibiotics — separate timing"],
        "Useful adjunct for diarrhea — not replacement for ORS/antibiotics when needed.",
        "LOW",
    ),
    "econorm": _e(
        "Econorm (Saccharomyces boulardii)",
        "Probiotic yeast",
        ["Gas", "Constipation"],
        ["Fungemia in critically ill IV lines (rare)"],
        ["Antifungals may reduce effect"],
        "Often given with antibiotics for diarrhea prevention as advised.",
        "LOW",
    ),
    "dulcoflex": _e(
        "Dulcoflex (Bisacodyl — common brand)",
        "Laxative",
        ["Cramping", "Diarrhea", "Electrolyte loss"],
        ["Severe dehydration", "Dependency if chronic misuse"],
        ["Diuretics"],
        "For short-term constipation — find cause if persistent.",
        "MEDIUM",
    ),
    "duphalac": _e(
        "Duphalac (Lactulose)",
        "Osmotic laxative",
        ["Bloating", "Gas", "Cramping"],
        ["Dehydration if dose too high"],
        ["None major"],
        "Also used in hepatic encephalopathy — different dosing.",
        "LOW",
    ),
    "rantac d": _e(
        "Rantac-D (Ranitidine + Domperidone typical)",
        "Acid reducer + Prokinetic",
        ["Headache", "Diarrhea", "Dry mouth"],
        ["QT issues (domperidone component)", "Arrhythmia (rare)"],
        ["QT drugs", "Ketoconazole"],
        "Composition brand-specific — read strip.",
        "MEDIUM",
    ),
    "pan d": _e(
        "Pan-D (Pantoprazole + Domperidone)",
        "PPI + Prokinetic",
        ["Headache", "Diarrhea", "Dizziness"],
        ["QT prolongation", "Low magnesium long-term"],
        ["QT meds", "Warfarin"],
        "Common for GERD symptoms — long-term PPI review needed.",
        "MEDIUM",
    ),
    "esomeprazole": _e(
        "Nexium / Esomeprazole",
        "PPI",
        ["Headache", "Nausea", "Gas"],
        ["Fracture risk long-term", "Kidney issues (rare)"],
        ["Clopidogrel", "Methotrexate"],
        "Take as directed before meals.",
        "MEDIUM",
    ),
    "tramadol": _e(
        "Tramadol (pain)",
        "Opioid-like analgesic",
        ["Nausea", "Dizziness", "Constipation", "Drowsiness"],
        ["Seizures", "Serotonin syndrome", "Respiratory depression"],
        ["SSRIs", "MAOIs", "Alcohol", "Benzodiazepines"],
        "Prescription-only in many places. High abuse/dependence risk.",
        "HIGH",
    ),
    "flexon": _e(
        "Flexon (Ibuprofen + Paracetamol)",
        "NSAID combo",
        ["Stomach pain", "Nausea"],
        ["GI bleeding", "Kidney injury"],
        ["Alcohol", "Blood thinners"],
        "Same class as Combiflam — take with food.",
        "HIGH",
    ),
    "sumo": _e(
        "Sumo (Paracetamol + Nimesulide in some regions)",
        "NSAID combo",
        ["Nausea", "Heartburn"],
        ["Liver injury", "GI bleeding"],
        ["Alcohol", "Other NSAIDs"],
        "Confirm composition — regional brands differ.",
        "HIGH",
    ),
    "nimulid": _e(
        "Nimulid (Nimesulide)",
        "NSAID",
        ["Nausea", "Dizziness"],
        ["Hepatotoxicity", "GI bleeding"],
        ["Alcohol", "Paracetamol combos"],
        "Restricted/banned in some countries.",
        "HIGH",
    ),
    "dolonex": _e(
        "Dolonex (Piroxicam — brand variants)",
        "NSAID",
        ["Stomach upset", "Rash", "Dizziness"],
        ["GI bleeding", "Kidney failure", "Stroke/MI risk"],
        ["Warfarin", "Lithium", "Alcohol"],
        "Often once-daily — still full NSAID cautions.",
        "HIGH",
    ),
    "wysolone": _e(
        "Wysolone (Prednisolone)",
        "Corticosteroid",
        ["Weight gain", "Mood changes", "Insomnia", "High sugar"],
        ["Infection risk", "Osteoporosis", "Adrenal suppression", "Cataracts"],
        ["NSAIDs", "Warfarin", "Vaccines (live)"],
        "Never stop suddenly after long use. Take with food. Follow taper schedule.",
        "HIGH",
    ),
    "montek lc": _e(
        "Montek LC (Montelukast + Levocetirizine)",
        "Allergy combo",
        ["Drowsiness (levocetirizine)", "Headache", "Fatigue"],
        ["Mood changes (montelukast — report)", "Urinary retention"],
        ["Alcohol", "CNS depressants"],
        "Evening dose common for allergies.",
        "MEDIUM",
    ),
    "levocet": _e(
        "Levocet (Levocetirizine)",
        "Antihistamine",
        ["Drowsiness", "Dry mouth", "Fatigue"],
        ["Rare palpitations"],
        ["Alcohol", "Sedatives"],
        "Less sedating than hydroxyzine but can still tire some users.",
        "LOW",
    ),
    "deriphyllin": _e(
        "Deriphyllin (Etophylline + Theophylline typical)",
        "Bronchodilator",
        ["Nausea", "Palpitations", "Insomnia"],
        ["Seizures (toxic levels)", "Arrhythmias"],
        ["Ciprofloxacin", "Erythromycin", "Smoking"],
        "Narrow therapeutic window — levels may be monitored.",
        "HIGH",
    ),
    "asthalin": _e(
        "Asthalin (Salbutamol)",
        "Bronchodilator inhaler",
        ["Tremor", "Palpitations", "Headache"],
        ["Severe hypokalemia", "Paradoxical bronchospasm (rare)"],
        ["Beta blockers (may oppose)", "Other stimulants"],
        "Overuse means poor control — see doctor for asthma plan.",
        "MEDIUM",
    ),
    "foracort": _e(
        "Foracort (Formoterol + Budesonide)",
        "LABA + ICS inhaler",
        ["Oral thrush", "Hoarseness", "Tremor"],
        ["Pneumonia risk long-term ICS", "Adrenal suppression high dose"],
        ["Strong CYP3A4 inhibitors"],
        "Rinse mouth after use. Not for acute attacks alone.",
        "MEDIUM",
    ),
    "duonase": _e(
        "Duonase nasal spray (Azelastine + Fluticasone typical)",
        "Antihistamine + steroid nasal",
        ["Bitter taste", "Nasal irritation", "Headache"],
        ["Epistaxis", "Local infection"],
        ["None major systemic typical"],
        "Use correct spray technique.",
        "LOW",
    ),
    "nazomac": _e(
        "Nazomac-F / Mometasone nasal",
        "Nasal corticosteroid",
        ["Nasal irritation", "Headache", "Nosebleed"],
        ["Septal perforation (rare)", "Glaucoma (rare systemic)"],
        ["None major"],
        "Regular use for allergic rhinitis — not instant like oral decongestants.",
        "LOW",
    ),
    "clopitop": _e(
        "Clopilet / Clopitop (Clopidogrel — brand names vary)",
        "Antiplatelet",
        ["Bleeding", "Bruising", "Diarrhea"],
        ["Major bleeding", "TTP (rare)"],
        ["NSAIDs", "Warfarin", "SSRIs"],
        "With aspirin in many heart protocols — bleeding risk.",
        "HIGH",
    ),
    "ecosprin": _e(
        "Ecosprin (Enteric-coated Aspirin)",
        "Antiplatelet",
        ["Stomach upset (less than plain)", "Bleeding tendency"],
        ["GI bleed", "Hemorrhagic stroke"],
        ["Warfarin", "NSAIDs"],
        "Enteric coating reduces but does not eliminate GI risk.",
        "HIGH",
    ),
    "atorva": _e(
        "Atorva / Atorlip (Atorvastatin)",
        "Statin",
        ["Muscle ache", "Headache", "Gas"],
        ["Rhabdomyolysis (rare)", "Liver enzyme rise"],
        ["Grapefruit (large amounts)", "Some antibiotics", "Fibrates"],
        "Report unexplained muscle pain. Liver tests as advised.",
        "MEDIUM",
    ),
    "rosuvas": _e(
        "Rosuvas (Rosuvastatin)",
        "Statin",
        ["Muscle pain", "Weakness", "Nausea"],
        ["Rhabdomyolysis", "Kidney issues with high dose"],
        ["Gemfibrozil", "Cyclosporine", "Warfarin"],
        "Asian patients sometimes need lower starting doses.",
        "MEDIUM",
    ),
    "shelcal": _e(
        "Shelcal (Calcium + Vitamin D)",
        "Calcium supplement",
        ["Constipation", "Gas"],
        ["Hypercalcemia if overdose", "Kidney stones predisposed"],
        ["Levothyroxine", "Iron", "Bisphosphonates — spacing"],
        "Take with meals per label; separate from some meds.",
        "LOW",
    ),
    "supradyn": _e(
        "Supradyn (Multivitamin)",
        "Supplement",
        ["Nausea", "Bright urine"],
        ["Iron/copper overload if duplicated"],
        ["Levodopa with iron"],
        "General multivitamin — not treatment for deficiencies alone without diagnosis.",
        "LOW",
    ),
    "polybion": _e(
        "Polybion (B-complex)",
        "Vitamin B supplement",
        ["Nausea if empty stomach"],
        ["Allergy (rare)"],
        ["None major"],
        "Often given with neuropathy support — treat cause too.",
        "LOW",
    ),
    "neurobion": _e(
        "Neurobion (B1 B6 B12)",
        "Neurotropic vitamins",
        ["Flushing", "Mild nausea"],
        ["Peripheral neuropathy from B6 megadose (rare)"],
        ["Levodopa interaction context"],
        "Use doses as advised for neuropathy.",
        "LOW",
    ),

    # ── Cold & Cough ──────────────────────────────────────────────
    "ascoril": _e(
        "Ascoril (Salbutamol + Bromhexine + Guaifenesin)",
        "Bronchodilator + Expectorant",
        ["Tremors", "Palpitations", "Nausea", "Dizziness"],
        ["Severe tachycardia", "Hypokalemia with high dose"],
        ["Beta-blockers (oppose effect)", "Digoxin", "Diuretics"],
        "Not for dry cough. Caution in heart disease and hypertension.",
        "MEDIUM",
    ),
    "alex syrup": _e(
        "Alex Syrup (Dextromethorphan + Chlorpheniramine + Guaifenesin)",
        "Cough suppressant combo",
        ["Drowsiness", "Dry mouth", "Dizziness"],
        ["Respiratory depression if overdosed", "Serotonin syndrome (with MAOIs)"],
        ["MAOIs", "Alcohol", "Sedatives"],
        "Do not exceed dose. Avoid in children under 2 without doctor advice.",
        "MEDIUM",
    ),
    "levocetirizine": _e(
        "Levocetirizine (e.g. Levocet, Xyzal)",
        "Antihistamine (2nd gen)",
        ["Mild drowsiness", "Dry mouth", "Headache"],
        ["Rare severe allergy", "Urinary retention"],
        ["Alcohol", "CNS depressants"],
        "Less sedating than older antihistamines. Caution in kidney disease.",
        "LOW",
    ),
    "montair lc": _e(
        "Montair-LC (Montelukast + Levocetirizine)",
        "Antihistamine + Leukotriene blocker",
        ["Drowsiness", "Dry mouth", "Headache"],
        ["Mood changes (montelukast)", "Rare severe allergy"],
        ["Alcohol", "CNS depressants", "Rifampin"],
        "Common for allergic rhinitis. Report mood/behaviour changes.",
        "MEDIUM",
    ),
    "naproxen": _e(
        "Naproxen (e.g. Naprosyn)",
        "NSAID",
        ["Stomach upset", "Heartburn", "Dizziness", "Headache"],
        ["GI bleeding", "Kidney injury", "Cardiovascular risk (long-term)"],
        ["Aspirin", "Warfarin", "Lithium", "Alcohol"],
        "Take with food. Longer half-life than ibuprofen — twice daily dosing.",
        "HIGH",
    ),

    # ── Antibiotics ───────────────────────────────────────────────
    "amoxicillin": _e(
        "Amoxicillin (e.g. Mox, Novamox)",
        "Penicillin antibiotic",
        ["Diarrhea", "Nausea", "Skin rash"],
        ["Severe allergic reaction (anaphylaxis)", "C. diff colitis"],
        ["Warfarin", "Methotrexate", "Oral contraceptives (minor)"],
        "Tell doctor if penicillin allergy. Complete full course.",
        "MEDIUM",
    ),
    "ciprofloxacin": _e(
        "Ciprofloxacin (e.g. Ciplox, Cifran)",
        "Fluoroquinolone antibiotic",
        ["Nausea", "Diarrhea", "Dizziness", "Headache"],
        ["Tendon rupture", "Peripheral neuropathy", "QT prolongation", "C. diff"],
        ["NSAIDs", "Theophylline", "Warfarin", "Antacids (reduce absorption)"],
        "Avoid in children/adolescents unless essential. Sun sensitivity. Take 2h apart from antacids.",
        "HIGH",
    ),
    "doxycycline": _e(
        "Doxycycline (e.g. Doxt, Biodoxi)",
        "Tetracycline antibiotic",
        ["Nausea", "Photosensitivity", "Esophageal irritation"],
        ["Severe photosensitivity", "Esophageal ulcer if not taken with water"],
        ["Antacids/iron/calcium (reduce absorption)", "Warfarin", "Oral contraceptives"],
        "Take upright with full glass of water. Avoid sun exposure. Not in pregnancy/children <8.",
        "HIGH",
    ),
    "cefixime": _e(
        "Cefixime (e.g. Taxim-O, Zifi)",
        "3rd gen Cephalosporin antibiotic",
        ["Diarrhea", "Nausea", "Stomach pain"],
        ["Severe allergy", "C. diff colitis", "Kidney issues"],
        ["Warfarin (may increase effect)", "Probenecid"],
        "Complete full course. Caution if penicillin allergy (cross-reactivity rare).",
        "MEDIUM",
    ),
    "ceftriaxone": _e(
        "Ceftriaxone (Injection — e.g. Monocef)",
        "3rd gen Cephalosporin (IV/IM)",
        ["Injection site pain", "Diarrhea", "Rash"],
        ["Severe allergy", "Biliary sludge", "C. diff"],
        ["Calcium-containing IV fluids (precipitate risk)", "Warfarin"],
        "Hospital/clinic use only. Not for self-administration.",
        "HIGH",
    ),
    "ofloxacin": _e(
        "Ofloxacin (e.g. Zanocin, Oflox)",
        "Fluoroquinolone antibiotic",
        ["Nausea", "Dizziness", "Headache", "Insomnia"],
        ["Tendon rupture", "QT prolongation", "Neuropathy"],
        ["Antacids", "NSAIDs", "Warfarin", "Theophylline"],
        "Avoid in children. Sun sensitivity. Space from antacids by 2h.",
        "HIGH",
    ),

    # ── Heart & BP ────────────────────────────────────────────────
    "atenolol": _e(
        "Atenolol (e.g. Tenormin, Aten)",
        "Beta-blocker (antihypertensive)",
        ["Fatigue", "Cold hands/feet", "Dizziness", "Slow heart rate"],
        ["Severe bradycardia", "Heart block", "Bronchospasm in asthmatics"],
        ["Calcium channel blockers", "Digoxin", "NSAIDs", "Insulin (masks hypoglycemia signs)"],
        "Never stop suddenly — taper under doctor supervision. Avoid in asthma.",
        "HIGH",
    ),
    "metoprolol": _e(
        "Metoprolol (e.g. Betaloc, Metolar)",
        "Cardioselective Beta-blocker",
        ["Fatigue", "Dizziness", "Bradycardia", "Cold extremities"],
        ["Heart block", "Severe bradycardia", "Worsening heart failure initially"],
        ["Verapamil", "Diltiazem", "Clonidine", "NSAIDs"],
        "Do not stop abruptly. More cardioselective than atenolol — safer in mild asthma.",
        "HIGH",
    ),
    "losartan": _e(
        "Losartan (e.g. Losar, Repace)",
        "ARB antihypertensive",
        ["Dizziness", "Fatigue", "High potassium"],
        ["Kidney failure", "Angioedema (rare)", "Severe hypotension"],
        ["Potassium supplements", "NSAIDs", "Lithium", "ACE inhibitors"],
        "Avoid in pregnancy. Monitor kidney function and potassium levels.",
        "MEDIUM",
    ),
    "ramipril": _e(
        "Ramipril (e.g. Cardace, Ramistar)",
        "ACE inhibitor",
        ["Dry persistent cough", "Dizziness", "Headache"],
        ["Angioedema (rare but serious)", "Kidney failure", "High potassium"],
        ["Potassium supplements", "NSAIDs", "Lithium", "ARBs"],
        "Avoid in pregnancy. Cough is common — switch to ARB if intolerable.",
        "HIGH",
    ),
    "clopidogrel": _e(
        "Clopidogrel (e.g. Clopilet, Plavix)",
        "Antiplatelet agent",
        ["Easy bruising", "Bleeding", "Stomach upset"],
        ["Serious bleeding (GI, brain)", "Thrombotic thrombocytopenic purpura (rare)"],
        ["Aspirin (increased bleeding)", "Omeprazole (reduced effect)", "NSAIDs", "Warfarin"],
        "Do not stop without doctor advice — risk of clot/heart attack. Avoid elective surgery without plan.",
        "HIGH",
    ),
    "atorvastatin": _e(
        "Atorvastatin (e.g. Atorva, Lipitor)",
        "Statin (cholesterol-lowering)",
        ["Muscle aches", "Headache", "Nausea", "Joint pain"],
        ["Rhabdomyolysis (rare — severe muscle breakdown)", "Liver injury (rare)"],
        ["Grapefruit juice", "Fibrates", "Niacin", "Cyclosporine", "Amlodipine (dose limit)"],
        "Report unexplained muscle pain immediately. Liver tests periodically.",
        "MEDIUM",
    ),

    # ── Diabetes ──────────────────────────────────────────────────
    "glimepiride": _e(
        "Glimepiride (e.g. Amaryl, Glimer)",
        "Sulfonylurea antidiabetic",
        ["Hypoglycemia", "Weight gain", "Nausea"],
        ["Severe hypoglycemia", "Allergic reaction"],
        ["Alcohol", "Beta-blockers (mask hypo signs)", "NSAIDs", "Warfarin"],
        "Take with first meal. Carry sugar. Dose adjustment needed in kidney disease.",
        "HIGH",
    ),
    "sitagliptin": _e(
        "Sitagliptin (e.g. Januvia, Istavel)",
        "DPP-4 inhibitor antidiabetic",
        ["Nasopharyngitis", "Headache", "Nausea"],
        ["Pancreatitis (rare)", "Severe joint pain (rare)", "Kidney issues"],
        ["Digoxin (minor)", "Insulin/sulfonylureas (hypoglycemia risk)"],
        "Dose reduction in kidney disease. Report severe abdominal pain.",
        "MEDIUM",
    ),
    "pioglitazone": _e(
        "Pioglitazone (e.g. Pioz, Actos)",
        "Thiazolidinedione antidiabetic",
        ["Weight gain", "Fluid retention", "Bone fractures"],
        ["Heart failure worsening", "Bladder cancer risk (long-term)", "Liver injury (rare)"],
        ["Insulin (increased hypoglycemia)", "Gemfibrozil"],
        "Avoid in heart failure. Monitor liver function. Not for bladder cancer history.",
        "HIGH",
    ),

    # ── Mental Health ─────────────────────────────────────────────
    "alprazolam": _e(
        "Alprazolam (e.g. Alprax, Restyl)",
        "Benzodiazepine (anxiolytic)",
        ["Drowsiness", "Dizziness", "Memory impairment", "Coordination problems"],
        ["Dependence/addiction", "Respiratory depression", "Severe sedation"],
        ["Alcohol", "Opioids", "Other CNS depressants", "Antifungals (increase levels)"],
        "High dependence potential. Do not stop abruptly — taper. Avoid driving.",
        "HIGH",
    ),
    "diazepam": _e(
        "Diazepam (e.g. Valium, Calmpose)",
        "Benzodiazepine",
        ["Drowsiness", "Muscle weakness", "Dizziness", "Confusion"],
        ["Respiratory depression", "Dependence", "Paradoxical agitation"],
        ["Alcohol", "Opioids", "Antidepressants", "Antifungals"],
        "Controlled substance. Short-term use only. Never stop abruptly.",
        "HIGH",
    ),
    "clonazepam": _e(
        "Clonazepam (e.g. Rivotril, Lonazep)",
        "Benzodiazepine (anticonvulsant/anxiolytic)",
        ["Drowsiness", "Dizziness", "Memory problems", "Coordination issues"],
        ["Respiratory depression", "Dependence", "Suicidal ideation (rare)"],
        ["Alcohol", "Opioids", "Other CNS depressants"],
        "Controlled substance. Do not stop suddenly — seizure risk. Avoid driving.",
        "HIGH",
    ),
    "sertraline": _e(
        "Sertraline (e.g. Zoloft, Serta)",
        "SSRI antidepressant",
        ["Nausea", "Insomnia or drowsiness", "Dry mouth", "Sexual dysfunction"],
        ["Serotonin syndrome", "Suicidal ideation (young patients — monitor)", "Bleeding risk"],
        ["MAOIs (dangerous)", "Tramadol", "Warfarin", "NSAIDs", "Lithium"],
        "Takes 2-4 weeks for effect. Do not stop abruptly. Monitor mood changes especially early.",
        "HIGH",
    ),
    "fluoxetine": _e(
        "Fluoxetine (e.g. Fludac, Prozac)",
        "SSRI antidepressant",
        ["Nausea", "Insomnia", "Headache", "Anxiety initially", "Sexual dysfunction"],
        ["Serotonin syndrome", "Suicidal ideation (monitor)", "QT prolongation"],
        ["MAOIs (dangerous — 14 day washout)", "Tramadol", "Warfarin", "Tamoxifen"],
        "Long half-life — less withdrawal. Takes weeks for effect. Monitor mood.",
        "HIGH",
    ),
    "escitalopram": _e(
        "Escitalopram (e.g. Nexito, Cipralex)",
        "SSRI antidepressant",
        ["Nausea", "Insomnia", "Dry mouth", "Sweating", "Sexual dysfunction"],
        ["Serotonin syndrome", "QT prolongation", "Suicidal ideation (monitor)"],
        ["MAOIs (dangerous)", "Tramadol", "NSAIDs", "Warfarin", "Cimetidine"],
        "Do not stop abruptly — taper. Takes 2-4 weeks for effect. Monitor mood.",
        "HIGH",
    ),

    # ── Muscle Relaxants ──────────────────────────────────────────
    "myospaz": _e(
        "Myospaz (Chlorzoxazone + Diclofenac typical)",
        "Muscle relaxant + NSAID combo",
        ["Drowsiness", "Dizziness", "Nausea", "Stomach upset"],
        ["Liver toxicity (chlorzoxazone)", "GI bleeding (diclofenac)"],
        ["Alcohol", "CNS depressants", "Other NSAIDs", "Warfarin"],
        "Avoid driving. Take with food. Short-term use for muscle spasm.",
        "HIGH",
    ),
    "thiocolchicoside": _e(
        "Thiocolchicoside (e.g. Myoril, Thiocol)",
        "Muscle relaxant",
        ["Drowsiness", "Dizziness", "Nausea", "Diarrhea"],
        ["Seizures at high dose", "Reproductive toxicity (avoid in pregnancy)"],
        ["Alcohol", "CNS depressants"],
        "Short-term use only (max 7 days oral). Avoid in pregnancy.",
        "MEDIUM",
    ),

    # ── Skin & Allergy ────────────────────────────────────────────
    "hydrocortisone": _e(
        "Hydrocortisone (topical/oral/injection)",
        "Corticosteroid",
        ["Skin thinning (topical)", "Weight gain (oral)", "Mood changes", "Increased appetite"],
        ["Adrenal suppression", "Osteoporosis (long-term)", "Immunosuppression", "Hyperglycemia"],
        ["NSAIDs", "Warfarin", "Diabetes meds", "Live vaccines"],
        "Do not stop oral steroids abruptly. Topical — avoid face/groin long-term.",
        "HIGH",
    ),
    "betnovate": _e(
        "Betnovate (Betamethasone topical)",
        "Potent topical corticosteroid",
        ["Skin thinning", "Stretch marks", "Acne", "Burning"],
        ["Adrenal suppression if overused", "Skin atrophy", "Steroid rosacea"],
        ["Other topical steroids"],
        "Do not use on face, groin, or underarms long-term. Thin skin areas — use sparingly.",
        "HIGH",
    ),
    "clotrimazole": _e(
        "Clotrimazole (e.g. Candid, Canesten)",
        "Antifungal (topical/vaginal)",
        ["Mild burning", "Itching", "Skin irritation"],
        ["Severe allergic reaction (rare)"],
        ["Tacrolimus (topical interaction)"],
        "External use. Complete full course even if symptoms improve.",
        "LOW",
    ),
    "permethrin": _e(
        "Permethrin (e.g. Scaboma, Elimite)",
        "Antiparasitic (scabies/lice)",
        ["Skin burning", "Itching", "Tingling"],
        ["Severe skin reaction (rare)", "Neurotoxicity if ingested"],
        ["None significant topical"],
        "Apply to whole body below neck. Wash off after 8-14 hours. Treat household contacts.",
        "LOW",
    ),
    "luliconazole": _e(
        "Luliconazole (e.g. Lulifin, Lulican)",
        "Antifungal (topical)",
        ["Mild burning", "Itching", "Erythema"],
        ["Severe allergic reaction (rare)"],
        ["None significant"],
        "For ringworm, athlete's foot. Apply beyond lesion edges. Complete course.",
        "LOW",
    ),

    # ── Vitamins & Supplements ────────────────────────────────────
    "vitamin d3": _e(
        "Vitamin D3 (Cholecalciferol — e.g. Calcirol, D-Rise)",
        "Fat-soluble vitamin supplement",
        ["Nausea at high dose", "Constipation", "Weakness"],
        ["Hypercalcemia (toxicity with megadose)", "Kidney stones"],
        ["Thiazide diuretics (increase calcium)", "Digoxin (hypercalcemia risk)"],
        "Fat-soluble — toxicity possible with excess. Test levels before high-dose supplementation.",
        "MEDIUM",
    ),
    "vitamin b12": _e(
        "Vitamin B12 (Cyanocobalamin/Methylcobalamin)",
        "Water-soluble vitamin",
        ["Mild diarrhea", "Itching (injection)"],
        ["Rare allergic reaction (injection form)"],
        ["Metformin (reduces B12 absorption)", "PPIs (long-term)"],
        "Deficiency common in vegetarians and metformin users. Safe at normal doses.",
        "LOW",
    ),
    "calcium tablets": _e(
        "Calcium Carbonate / Citrate (e.g. Shelcal, Calcimax)",
        "Mineral supplement",
        ["Constipation", "Gas", "Bloating"],
        ["Hypercalcemia with excess", "Kidney stones in predisposed"],
        ["Iron (separate by 2h)", "Thyroid meds", "Tetracyclines", "Bisphosphonates"],
        "Calcium carbonate needs food; citrate does not. Space from other meds.",
        "LOW",
    ),
    "zincovit": _e(
        "Zincovit (Zinc + Multivitamins)",
        "Multivitamin + Zinc supplement",
        ["Nausea", "Metallic taste", "Stomach upset"],
        ["Zinc toxicity with excess (nausea, vomiting, immune suppression)"],
        ["Copper absorption reduced by zinc", "Antibiotics (tetracyclines, quinolones)"],
        "Supplement — not a substitute for balanced diet.",
        "LOW",
    ),

    # ── Emergency / Critical ──────────────────────────────────────
    "adrenaline": _e(
        "Adrenaline / Epinephrine (Injection)",
        "Emergency vasopressor / Anaphylaxis treatment",
        ["Palpitations", "Tremors", "Anxiety", "Headache", "Hypertension"],
        ["Severe hypertension", "Cardiac arrhythmia", "Pulmonary edema"],
        ["Beta-blockers (oppose effect)", "MAOIs", "Tricyclic antidepressants"],
        "EMERGENCY USE ONLY. Administered by healthcare professionals. Auto-injector (EpiPen) for anaphylaxis.",
        "HIGH",
    ),
    "nitroglycerin": _e(
        "Nitroglycerin / GTN (e.g. Sorbitrate, Nitrostat)",
        "Nitrate (antianginal)",
        ["Headache", "Dizziness", "Flushing", "Low BP"],
        ["Severe hypotension", "Syncope", "Reflex tachycardia"],
        ["Sildenafil/Tadalafil (DANGEROUS — severe hypotension)", "Alcohol", "Other BP meds"],
        "NEVER combine with PDE5 inhibitors (Viagra etc.) — life-threatening BP drop. Sit/lie when taking.",
        "HIGH",
    ),
    "heparin": _e(
        "Heparin (Injection — anticoagulant)",
        "Anticoagulant (blood thinner)",
        ["Bleeding at injection site", "Bruising"],
        ["Major bleeding", "Heparin-induced thrombocytopenia (HIT)", "Osteoporosis (long-term)"],
        ["Aspirin", "NSAIDs", "Warfarin", "Clopidogrel"],
        "HOSPITAL USE ONLY. Requires monitoring (aPTT). Antidote: Protamine sulfate.",
        "HIGH",
    ),
    "morphine": _e(
        "Morphine (Opioid analgesic)",
        "Strong opioid analgesic",
        ["Nausea", "Constipation", "Drowsiness", "Dizziness", "Dry mouth"],
        ["Respiratory depression (life-threatening)", "Dependence/addiction", "Coma"],
        ["Alcohol", "Benzodiazepines", "MAOIs", "Other CNS depressants"],
        "CONTROLLED SUBSTANCE. Hospital/palliative use. Antidote: Naloxone. Never combine with alcohol.",
        "HIGH",
    ),
    "atropine": _e(
        "Atropine (Injection/Eye drops)",
        "Anticholinergic (emergency/ophthalmology)",
        ["Dry mouth", "Blurred vision", "Urinary retention", "Tachycardia", "Flushing"],
        ["Severe tachycardia", "Glaucoma worsening", "Hyperthermia", "Confusion"],
        ["Antihistamines", "Tricyclics", "Other anticholinergics"],
        "MEDICAL USE ONLY. Used for bradycardia, organophosphate poisoning, eye dilation.",
        "HIGH",
    ),
}

# Aliases / common spellings → same key
_ALIASES = {
    "rentac": "rantac",
    "rantac": "rantac",
    "paracetamol": "crocin",
    "acetaminophen": "crocin",
    "dolo650": "dolo 650",
    "dolo-650": "dolo 650",
    "combiflam": "combiflam",
    "nicip+": "nicip plus",
    "nicip plus": "nicip plus",
    "diclogem": "diclogem",
    "oxalgin-d": "oxalgin",
    "oxalgin d": "oxalgin",
    "disprin": "disprin",
    "pan d": "pan d",
    "pantocid d": "pan d",
    "montek lc": "montek lc",
    "vicks action 500": "vicks action 500",
    "vicks action 500+": "vicks action 500",
    "clopilet": "clopitop",
    "ecosprin gold": "ecosprin",
    "amlong": "amlong",
    "glycomet gp": "glycomet",
    "mixtard": "insulin",
    "huminsulin": "insulin",
    "basalog": "insulin",
    "lantus": "insulin",
    "novorapid": "insulin",
    "okacet": "cetirizine",
    "ctz": "cetirizine",
    "avil": "avil",
    "benadryl": "honitus",
    "action 500": "vicks action 500",
    "amolong": "amlong",
    "amlodipine": "amlong",
    "paracetamol": "crocin",
    "pcm": "crocin",
    "omeprazole": "omez",
    "pantoprazole": "pantocid",
    "telmisartan": "telma",
    "azithromycin": "azithral",
    "metronidazole": "metrogyl",
    "diclofenac": "voveran",
    "ibuprofen": "ibugesic",
    "domperidone": "domstal",
    "ondansetron": "ondem",
    "fexofenadine": "allegra",
    "montelukast": "montair",
    "levothyroxine": "thyronorm",
    "bisacodyl": "dulcoflex",
    "lactulose": "duphalac",
    "loperamide": "roko",
    "nimesulide": "nicip",
    "aceclofenac": "zerodol",
    "drotaverine": "drotin",
    "norfloxacin": "norflox",
    "ranitidine": "rantac",
    "pheniramine": "avil",
    "mefenamic acid": "meftal spas",
    "dicyclomine": "cyclopam",
    # New aliases
    "amoxycillin": "amoxicillin",
    "novamox": "amoxicillin",
    "mox": "amoxicillin",
    "ciplox": "ciprofloxacin",
    "cifran": "ciprofloxacin",
    "cipro": "ciprofloxacin",
    "doxt": "doxycycline",
    "taxim": "cefixime",
    "zifi": "cefixime",
    "monocef": "ceftriaxone",
    "zanocin": "ofloxacin",
    "oflox": "ofloxacin",
    "tenormin": "atenolol",
    "aten": "atenolol",
    "betaloc": "metoprolol",
    "metolar": "metoprolol",
    "losar": "losartan",
    "repace": "losartan",
    "cardace": "ramipril",
    "ramistar": "ramipril",
    "clopilet": "clopidogrel",
    "plavix": "clopidogrel",
    "atorva": "atorvastatin",
    "lipitor": "atorvastatin",
    "amaryl": "glimepiride",
    "glimer": "glimepiride",
    "januvia": "sitagliptin",
    "istavel": "sitagliptin",
    "pioz": "pioglitazone",
    "actos": "pioglitazone",
    "alprax": "alprazolam",
    "restyl": "alprazolam",
    "valium": "diazepam",
    "calmpose": "diazepam",
    "rivotril": "clonazepam",
    "lonazep": "clonazepam",
    "zoloft": "sertraline",
    "serta": "sertraline",
    "fludac": "fluoxetine",
    "prozac": "fluoxetine",
    "nexito": "escitalopram",
    "cipralex": "escitalopram",
    "myoril": "thiocolchicoside",
    "thiocol": "thiocolchicoside",
    "candid": "clotrimazole",
    "canesten": "clotrimazole",
    "scaboma": "permethrin",
    "lulifin": "luliconazole",
    "lulican": "luliconazole",
    "calcirol": "vitamin d3",
    "d-rise": "vitamin d3",
    "d rise": "vitamin d3",
    "shelcal": "calcium tablets",
    "calcimax": "calcium tablets",
    "epinephrine": "adrenaline",
    "epipen": "adrenaline",
    "sorbitrate": "nitroglycerin",
    "nitrostat": "nitroglycerin",
    "gtn": "nitroglycerin",
    "alex": "alex syrup",
    "levocet": "levocetirizine",
    "xyzal": "levocetirizine",
    "betamethasone": "betnovate",
    "hydrocort": "hydrocortisone",
}


def lookup_drug(drug_name: str):
    """Return drug info dict or None. Handles spaces, common typos, aliases."""
    if not drug_name or not str(drug_name).strip():
        return None
    q = str(drug_name).strip().lower()
    q = " ".join(q.split())
    if q in _BASE:
        return _BASE[q]
    if q in _ALIASES:
        k = _ALIASES[q]
        return _BASE.get(k)
    # Direct alias target may be multi-word
    if q.replace(" ", "") in _ALIASES:
        return _BASE.get(_ALIASES[q.replace(" ", "")])
    # Try without spaces match to base keys
    q_compact = q.replace(" ", "")
    for key, val in _BASE.items():
        if key.replace(" ", "") == q_compact:
            return val
    # Substring match: user types "crocin 500" → crocin
    for key in sorted(_BASE.keys(), key=len, reverse=True):
        if key in q or q in key:
            if len(key) >= 4 and len(q) >= 3:
                return _BASE[key]
    return None
